import { NextRequest, NextResponse } from "next/server";
import { supabase } from "@/lib/supabase";
import { getEmbeddingModel, groqClient } from "@/lib/gemini";

export async function POST(req: NextRequest) {
  try {
    const { question, fileId } = await req.json();

    if (!question || !fileId) {
      return NextResponse.json(
        { error: "Missing question or fileId" },
        { status: 400 }
      );
    }

    console.log("🔍 Searching for relevant chunks...");

    // 1. Convert question to vector using Gemini Embeddings
    const embeddingModel = getEmbeddingModel();
    const embedResult = await embeddingModel.embedContent(question);
    const questionVector = embedResult.embedding.values;

    // 2. Search Supabase for matching chunks
    const { data: chunks, error: searchError } = await supabase.rpc(
      "match_documents",
      {
        query_embedding: questionVector,
        match_file_id: fileId,
        match_count: 5,
      }
    );

    if (searchError) throw searchError;

    console.log(`📚 Found ${chunks?.length || 0} relevant chunks`);

    // 3. Build context
    const context =
      chunks?.map((chunk: any) => chunk.content).join("\n\n") ||
      "No relevant context found.";

    // 4. Use Groq for chat (no daily limits!)
    const completion = await groqClient.chat.completions.create({
      model: "llama-3.3-70b-versatile",
      messages: [
        {
          role: "system",
          content: `You are a helpful assistant that answers questions based ONLY on the provided document context. 
          If the answer is not found in the context, say "I couldn't find that information in the document."
          Do not make up information outside of the context.`,
        },
        {
          role: "user",
          content: `Document Context:\n${context}\n\nUser Question: ${question}`,
        },
      ],
      temperature: 0.3,
      max_tokens: 1024,
    });

    const answer =
      completion.choices[0]?.message?.content ||
      "Sorry, I could not generate an answer.";

    console.log("✅ Answer generated by Groq Llama 3!");

    return NextResponse.json({
      answer,
      chunksUsed: chunks?.length || 0,
      model: "Groq Llama 3",
    });
  } catch (error: any) {
    console.error("❌ Chat Error:", error);
    return NextResponse.json(
      { error: error.message || "Failed to generate answer" },
      { status: 500 }
    );
  }
}